// <auto-generated />
using System;
using Cemidex.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cemidex.Migrations
{
    [DbContext(typeof(CemidexContext))]
    [Migration("20220301111223_Versao1")]
    partial class Versao1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Cemidex.Models.Cova", b =>
                {
                    b.Property<int>("IdCova")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRequerente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCova");

                    b.ToTable("Covas");
                });

            modelBuilder.Entity("Cemidex.Models.Falecido", b =>
                {
                    b.Property<int>("IdFalecido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CertidaoObito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEnterro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataObito")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCova")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRequerente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Idade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistroObito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("IdFalecido");

                    b.ToTable("Falecidos");
                });

            modelBuilder.Entity("Cemidex.Models.Requerente", b =>
                {
                    b.Property<int>("IdRequerente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdRequerente");

                    b.ToTable("Requerentes");
                });

            modelBuilder.Entity("Cemidex.Models.Sepultamento", b =>
                {
                    b.Property<int>("IdSepultamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataExumacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSepultamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCova")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdFalecido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdSepultamento");

                    b.ToTable("Sepultamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
